version: '3.3'
services:
  db:
    image: mysql:5.7
    ports:
      - '3307:3306'
    command: mysqld --sql_mode="IGNORE_SPACE,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - my-db:/var/lib/mysql

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - backend

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - backend



volumes:
  my-db:

networks:
    backend:
        driver: bridge